service: serverless

provider:
  name: aws
  runtime: nodejs14.x
  #profile: femasters
  region: us-west-1
  stage: dev
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

functions:
  helloWorld:
    handler: src/helloworld.handler
